plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2.1
  SuggestExtensions: false
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/PredicateName:
  Enabled: false

RSpec:
  SpecFilePathFormat:
    Enabled: true
  SpecFilePathSuffix:
    Enabled: true
  ExampleLength:
    Enabled: false
  ExampleWording:
    Enabled: false
  MultipleExpectations:
    Enabled: false
  NoExpectationExample:
    Enabled: false
  BeforeAfterAll:
    Enabled: false
  EmptyExampleGroup:
    Enabled: false
  HookArgument:
    Enabled: false
  RepeatedExample:
    Enabled: false
  LeakyConstantDeclaration:
    Enabled: false
  InstanceVariable:
    Enabled: false

Naming/FileName:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/RedundantConditional:
  Enabled: false

Style/IfWithBooleanLiteralBranches:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
