# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'dry-struct'
gem 'dry-types'
gem 'dry-validation'
gem 'dry-container'
gem 'dry-auto_inject'
gem 'dry-monads'
gem 'puma'
gem 'rake'
gem 'rom'
gem 'rom-sql'
gem 'sqlite3'
gem 'sequel'

group :development, :test do
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rspec'
end
