# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'dry-struct'
gem 'dry-types'
gem 'dry-validation'
gem 'dry-monads'
gem 'hanami-api'
gem 'puma'

group :development, :test do
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rspec'
end
